### ISSUE TITLE
Unable to update config on esphome flashed 2.5i board w/ Sec+1.0

### ISSUE THREAD

**Issue by PedanticAvenger** [ratgdo/esphome-ratgdo#186]
Flashm, connection to wireless and adoption into ESPHome dashboard works just fine.  
Device shows as online and all sensors show up in HA.

When trying to rename the device the upload attempt fails with the following log output:
```
INFO Reading configuration /config/esphome/ratgdov25i-86b4b5.yaml...
INFO Updating https://github.com/ratgdo/esphome-ratgdo@None
ERROR Unable to load component ratgdo:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/74f605c3/components/ratgdo/__init__.py", line 49, in <module>
    cv.none, pins.gpio_input_pin_schema
AttributeError: module 'esphome.config_validation' has no attribute 'none'
ERROR Unable to load component ratgdo.sensor:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/74f605c3/components/ratgdo/__init__.py", line 49, in <module>
    cv.none, pins.gpio_input_pin_schema
AttributeError: module 'esphome.config_validation' has no attribute 'none'
ERROR Unable to load component ratgdo.sensor:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/74f605c3/components/ratgdo/__init__.py", line 49, in <module>
    cv.none, pins.gpio_input_pin_schema
AttributeError: module 'esphome.config_validation' has no attribute 'none'
ERROR Unable to load component ratgdo.lock:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/74f605c3/components/ratgdo/__init__.py", line 49, in <module>
    cv.none, pins.gpio_input_pin_schema
AttributeError: module 'esphome.config_validation' has no attribute 'none'
ERROR Unable to load component ratgdo.switch:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/74f605c3/components/ratgdo/__init__.py", line 49, in <module>
    cv.none, pins.gpio_input_pin_schema
AttributeError: module 'esphome.config_validation' has no attribute 'none'
ERROR Unable to load component ratgdo.binary_sensor:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/74f605c3/components/ratgdo/__init__.py", line 49, in <module>
    cv.none, pins.gpio_input_pin_schema
AttributeError: module 'esphome.config_validation' has no attribute 'none'
ERROR Unable to load component ratgdo.binary_sensor:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/74f605c3/components/ratgdo/__init__.py", line 49, in <module>
    cv.none, pins.gpio_input_pin_schema
AttributeError: module 'esphome.config_validation' has no attribute 'none'
ERROR Unable to load component ratgdo.binary_sensor:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/74f605c3/components/ratgdo/__init__.py", line 49, in <module>
    cv.none, pins.gpio_input_pin_schema
AttributeError: module 'esphome.config_validation' has no attribute 'none'
ERROR Unable to load component ratgdo.binary_sensor:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/74f605c3/components/ratgdo/__init__.py", line 49, in <module>
    cv.none, pins.gpio_input_pin_schema
AttributeError: module 'esphome.config_validation' has no attribute 'none'
ERROR Unable to load component ratgdo.number:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/74f605c3/components/ratgdo/__init__.py", line 49, in <module>
    cv.none, pins.gpio_input_pin_schema
AttributeError: module 'esphome.config_validation' has no attribute 'none'
ERROR Unable to load component ratgdo.number:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/74f605c3/components/ratgdo/__init__.py", line 49, in <module>
    cv.none, pins.gpio_input_pin_schema
AttributeError: module 'esphome.config_validation' has no attribute 'none'
ERROR Unable to load component ratgdo.number:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/74f605c3/components/ratgdo/__init__.py", line 49, in <module>
    cv.none, pins.gpio_input_pin_schema
AttributeError: module 'esphome.config_validation' has no attribute 'none'
ERROR Unable to load component ratgdo.number:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/74f605c3/components/ratgdo/__init__.py", line 49, in <module>
    cv.none, pins.gpio_input_pin_schema
AttributeError: module 'esphome.config_validation' has no attribute 'none'
ERROR Unable to load component ratgdo.cover:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/74f605c3/components/ratgdo/__init__.py", line 49, in <module>
    cv.none, pins.gpio_input_pin_schema
AttributeError: module 'esphome.config_validation' has no attribute 'none'
ERROR Unable to load component ratgdo.light:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/74f605c3/components/ratgdo/__init__.py", line 49, in <module>
    cv.none, pins.gpio_input_pin_schema
AttributeError: module 'esphome.config_validation' has no attribute 'none'
INFO Detected timezone 'America/Edmonton'
Failed config

ratgdo: [source /config/esphome/.esphome/packages/74f605c3/base.yaml:13]
  
  Component not found: ratgdo.
  id: ratgdov25i
  input_gdo_pin: D2
  output_gdo_pin: D1
  input_obst_pin: D7
  on_sync_failed: 
    then: 
      - homeassistant.service: 
          service: persistent_notification.create
          data: 
            title: Garage Door Ctrl sync failed
            message: Failed to communicate with garage opener on startup.
            notification_id: esphome_ratgdo_ratgdov25i_sync_failed
sensor.ratgdo: [source /config/esphome/.esphome/packages/74f605c3/base.yaml:45]
  
  Platform not found: 'sensor.ratgdo'.
  platform: ratgdo
  id: ratgdov25i_openings
  type: openings
  entity_category: diagnostic
  ratgdo_id: ratgdov25i
  name: Openings
  unit_of_measurement: openings
  icon: mdi:open-in-app
sensor.ratgdo: [source /config/esphome/.esphome/packages/74f605c3/base.yaml:53]
  
  Platform not found: 'sensor.ratgdo'.
  platform: ratgdo
  id: ratgdov25i_paired_devices_total
  type: paired_devices_total
  entity_category: diagnostic
  ratgdo_id: ratgdov25i
  name: Paired Devices
  icon: mdi:remote
lock.ratgdo: [source /config/esphome/.esphome/packages/74f605c3/base.yaml:62]
  
  Platform not found: 'lock.ratgdo'.
  platform: ratgdo
  id: ratgdov25i_lock_remotes
  ratgdo_id: ratgdov25i
  name: Lock remotes
switch.ratgdo: [source /config/esphome/.esphome/packages/74f605c3/base.yaml:86]
  
  Platform not found: 'switch.ratgdo'.
  platform: ratgdo
  id: ratgdov25i_learn
  type: learn
  ratgdo_id: ratgdov25i
  name: Learn
  icon: mdi:plus-box
  entity_category: config
binary_sensor.ratgdo: [source /config/esphome/.esphome/packages/74f605c3/base.yaml:95]
  
  Platform not found: 'binary_sensor.ratgdo'.
  platform: ratgdo
  type: motion
  id: ratgdov25i_motion
  ratgdo_id: ratgdov25i
  name: Motion
  device_class: motion
binary_sensor.ratgdo: [source /config/esphome/.esphome/packages/74f605c3/base.yaml:101]
  
  Platform not found: 'binary_sensor.ratgdo'.
  platform: ratgdo
  type: obstruction
  id: ratgdov25i_obstruction
  ratgdo_id: ratgdov25i
  name: Obstruction
  device_class: problem
  on_press: 
    - switch.turn_on: ratgdov25i_status_obstruction
  on_release: 
    - switch.turn_off: ratgdov25i_status_obstruction
binary_sensor.ratgdo: [source /config/esphome/.esphome/packages/74f605c3/base.yaml:111]
  
  Platform not found: 'binary_sensor.ratgdo'.
  platform: ratgdo
  type: button
  id: ratgdov25i_button
  ratgdo_id: ratgdov25i
  name: Button
  entity_category: diagnostic
binary_sensor.ratgdo: [source /config/esphome/.esphome/packages/74f605c3/base.yaml:117]
  
  Platform not found: 'binary_sensor.ratgdo'.
  platform: ratgdo
  type: motor
  id: ratgdov25i_motor
  ratgdo_id: ratgdov25i
  name: Motor
  device_class: running
  entity_category: diagnostic
number.ratgdo: [source /config/esphome/.esphome/packages/74f605c3/base.yaml:176]
  
  Platform not found: 'number.ratgdo'.
  platform: ratgdo
  id: ratgdov25i_rolling_code_counter
  type: rolling_code_counter
  entity_category: config
  ratgdo_id: ratgdov25i
  name: Rolling code counter
  mode: box
  unit_of_measurement: codes
number.ratgdo: [source /config/esphome/.esphome/packages/74f605c3/base.yaml:185]
  
  Platform not found: 'number.ratgdo'.
  platform: ratgdo
  id: ratgdov25i_opening_duration
  type: opening_duration
  entity_category: config
  ratgdo_id: ratgdov25i
  name: Opening duration
  unit_of_measurement: s
number.ratgdo: [source /config/esphome/.esphome/packages/74f605c3/base.yaml:193]
  
  Platform not found: 'number.ratgdo'.
  platform: ratgdo
  id: ratgdov25i_closing_duration
  type: closing_duration
  entity_category: config
  ratgdo_id: ratgdov25i
  name: Closing duration
  unit_of_measurement: s
number.ratgdo: [source /config/esphome/.esphome/packages/74f605c3/base.yaml:201]
  
  Platform not found: 'number.ratgdo'.
  platform: ratgdo
  id: ratgdov25i_client_id
  type: client_id
  entity_category: config
  ratgdo_id: ratgdov25i
  name: Client ID
  mode: box
cover.ratgdo: [source /config/esphome/.esphome/packages/74f605c3/base.yaml:210]
  
  Platform not found: 'cover.ratgdo'.
  platform: ratgdo
  id: ratgdov25i_garage_door
  device_class: garage
  name: Door
  ratgdo_id: ratgdov25i
  on_closed: 
    - switch.turn_off: ratgdov25i_status_door
  on_open: 
    - switch.turn_on: ratgdov25i_status_door
light.ratgdo: [source /config/esphome/.esphome/packages/74f605c3/base.yaml:221]
  
  Platform not found: 'light.ratgdo'.
  platform: ratgdo
  id: ratgdov25i_light
  name: Light
  ratgdo_id: ratgdov25i
```

**Comment by bdraco** [comment]
You're running an old version of the dashboard, as new dashboard images are based on python, 3.11

**Comment by PedanticAvenger** [comment]
Argh. Thanks. Been running Dev of dashboard and thought it would stay ahead but something slipped. Reverted to current regular release and life was good.
